INSERT INTO authors (name, birthplace, birthday, created_at, updated_at) VALUES
('John Smith', 'New York', '1975-03-15', NOW(), NOW()),
('Emily Johnson', 'London', '1982-07-22', NOW(), NOW()),
('Michael Brown', 'Chicago', '1968-12-03', NOW(), NOW()),
('Sarah Davis', 'Sydney', '1990-05-18', NOW(), NOW()),
('Robert Wilson', 'Toronto', '1979-11-07', NOW(), NOW()),
('Lisa Anderson', 'Boston', '1985-09-12', NOW(), NOW()),
('David Taylor', 'Seattle', '1972-04-25', NOW(), NOW()),
('Jennifer White', 'Paris', '1988-01-30', NOW(), NOW()),
('Mark Thompson', 'Berlin', '1976-08-14', NOW(), NOW()),
('Amy Martinez', 'Madrid', '1993-06-08', NOW(), NOW()),
('James Lee', 'Tokyo', '1981-10-19', NOW(), NOW()),
('Rachel Green', 'Rome', '1987-02-27', NOW(), NOW()),
('Thomas Clark', 'Amsterdam', '1970-12-11', NOW(), NOW()),
('Jessica Adams', 'Vienna', '1991-03-03', NOW(), NOW()),
('Daniel Moore', 'Dublin', '1983-07-16', NOW(), NOW()),
('Kevin Scott', 'Phoenix', '1984-05-21', NOW(), NOW()),
('Laura King', 'Denver', '1977-09-08', NOW(), NOW()),
('Peter Hall', 'Atlanta', '1989-01-14', NOW(), NOW()),
('Michelle Wright', 'Portland', '1973-11-29', NOW(), NOW()),
('Steven Lopez', 'Miami', '1986-04-06', NOW(), NOW()),
('Nicole Hill', 'Nashville', '1992-08-23', NOW(), NOW()),
('Christopher Young', 'Austin', '1978-02-17', NOW(), NOW()),
('Amanda Walker', 'San Diego', '1995-06-30', NOW(), NOW()),
('Brian Allen', 'Cleveland', '1971-10-04', NOW(), NOW()),
('Stephanie Turner', 'Pittsburgh', '1980-12-19', NOW(), NOW()),
('Ryan Phillips', 'Detroit', '1987-03-26', NOW(), NOW()),
('Melissa Campbell', 'Minneapolis', '1974-07-11', NOW(), NOW()),
('Justin Parker', 'Tampa', '1991-09-02', NOW(), NOW()),
('Rebecca Evans', 'Osaka', '1983-01-28', NOW(), NOW()),
('Andrew Collins', 'Houston', '1976-05-15', NOW(), NOW());

INSERT INTO books (title, author_id, published_date, description, created_at, updated_at) VALUES
('The Great Adventure', 1, '2020-03-15', 'An exciting story about a young explorer who discovers a hidden world full of mysteries and ancient secrets that change everything.', NOW(), NOW()),
('Digital Dreams', 2, '2021-07-10', 'A futuristic tale exploring the complex relationship between humans and artificial intelligence in our rapidly changing digital age.', NOW(), NOW()),
('Ocean Depths', 3, '2019-12-22', 'A thrilling underwater adventure that takes readers to the deepest and most mysterious parts of our vast oceans.', NOW(), NOW()),
('Mountain Peaks', 1, '2022-05-08', 'An inspiring story about climbing the highest mountains while overcoming personal challenges and discovering inner strength.', NOW(), NOW()),
('City Lights', 4, '2021-09-30', 'A romantic story set in the bustling streets of a modern city filled with dreams, possibilities, and unexpected encounters.', NOW(), NOW()),
('Forest Whispers', 5, '2020-11-14', 'A magical tale about ancient forests and the mysterious creatures that protect them from various modern threats.', NOW(), NOW()),
('Space Journey', 2, '2023-02-28', 'An epic science fiction adventure through distant galaxies, exploring alien civilizations and cosmic mysteries beyond imagination.', NOW(), NOW()),
('Desert Winds', 3, '2022-08-17', 'A gripping survival story in the harsh desert environment where every decision could mean the difference between life and death.', NOW(), NOW()),
('River Song', 6, '2021-04-12', 'A peaceful journey along a winding river that reveals the beauty and tranquility of nature in its purest form.', NOW(), NOW()),
('Sky Dancer', 7, '2020-08-05', 'An uplifting story about following dreams and reaching for the stars despite obstacles and challenges along the way.', NOW(), NOW()),
('Fire Storm', 8, '2023-01-20', 'An intense action adventure featuring brave heroes facing dangerous natural disasters and fighting against impossible odds.', NOW(), NOW()),
('Ice Palace', 9, '2019-06-18', 'A fantasy adventure set in a frozen kingdom where magic and reality blend together in unexpected and wonderful ways.', NOW(), NOW()),
('Thunder Valley', 10, '2022-03-09', 'A western adventure story filled with courage, friendship, and the spirit of the American frontier during challenging times.', NOW(), NOW()),
('Golden Fields', 11, '2021-11-25', 'A heartwarming tale about rural life, family traditions, and the simple pleasures found in countryside living and farming.', NOW(), NOW()),
('Silver Moon', 12, '2020-07-13', 'A mysterious story that unfolds under the light of a full moon, revealing secrets and magic hidden in the darkness.', NOW(), NOW()),
('Crystal Cave', 13, '2022-09-14', 'A mysterious adventure deep underground where ancient crystals hold the power to change the world and unlock hidden secrets.', NOW(), NOW()),
('Wind Walker', 14, '2021-02-03', 'A spiritual journey across vast plains where the wind carries messages from ancestors and guides travelers to their destiny.', NOW(), NOW()),
('Star Bridge', 15, '2023-06-21', 'A science fiction epic about building bridges between distant worlds and connecting civilizations across the galaxy.', NOW(), NOW()),
('Shadow Dance', 16, '2020-10-07', 'A thrilling mystery where shadows come alive and dance through the night, revealing clues to an ancient conspiracy.', NOW(), NOW()),
('Eagle Flight', 17, '2022-01-19', 'An inspiring story about soaring high above challenges and finding freedom through courage and determination.', NOW(), NOW()),
('Wolf Pack', 18, '2021-12-08', 'A survival adventure about the bonds of family and loyalty in the wild wilderness of the northern mountains.', NOW(), NOW()),
('Phoenix Rising', 19, '2023-04-15', 'A powerful tale of rebirth and transformation where heroes rise from the ashes to face their greatest challenges.', NOW(), NOW()),
('Dragon Quest', 20, '2020-09-26', 'A fantasy adventure featuring brave knights on a quest to find ancient dragons and restore balance to the kingdom.', NOW(), NOW()),
('Ocean Pearl', 21, '2022-07-04', 'A treasure hunting adventure beneath the waves where divers search for legendary pearls with magical properties.', NOW(), NOW()),
('Mountain Spirit', 22, '2021-05-17', 'A mystical journey into the heart of ancient mountains where spirits guide lost souls back to their true path.', NOW(), NOW()),
('Forest Guardian', 23, '2023-08-11', 'An environmental adventure about protecting ancient woodlands from destruction and preserving nature for future generations.', NOW(), NOW()),
('Desert Mirage', 24, '2020-03-29', 'A mysterious tale where reality and illusion blur together in the endless sands of an unforgiving desert landscape.', NOW(), NOW()),
('River Dreams', 25, '2022-11-06', 'A peaceful story about following dreams downstream and discovering the true meaning of happiness and contentment.', NOW(), NOW()),
('Sky Castle', 26, '2021-08-22', 'A fantasy adventure set in a floating castle where magic rules and brave heroes must save the kingdom from darkness.', NOW(), NOW()),
('Storm Rider', 27, '2023-03-17', 'An action-packed adventure about riding the winds of change and facing the storms of life with courage and hope.', NOW(), NOW());